# Tensor
   - torch.Tensor  = the central class. Set its attribute .requires_grad as True to track all operations on it
   - .backward() =  When finish your computation and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.
   -  The gradient for this tensor will be accumulated into .grad attribute.
   - .detach() = To stop a tensor from tracking history
   - torch.no_grad(): This can be particularly helpful when evaluating a model because the model may have trainable parameters with requires_grad=True, but for which we don’t need the gradients.

In [1]:
from __future__ import print_function
import torch

# Create a tensor

In [2]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [3]:
# Add a Tensor with number
y = x + 2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


- #### 'y' was create as a result of an operation
    -  Each tensor has a .grad_fn attribute that references a Function that has created the Tensor (except for Tensors created by the user - their grad_fn is None)


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


 - #### .requires_grad_( ... ) 
     - changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to True if not given.

In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


# Gradients

### - Let’s backprop now
    - Because out contains a single scalar.
    - out.backward() is equivalent to out.backward(torch.tensor(1)).
### - The autograd tape 
    - Will remember all the operations it executed, and in the backward phase, it will replay the operations.

In [7]:
out.backward()
print(x.grad)

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [8]:
# Can do many things with autograd
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([  897.0240,   725.4637,  1032.7438])


In [19]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([  1638.4001,  14540.7998,      1.6384])


In [20]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
