# Tensors

初期化されてないメモリとして、一つのTensorのサイズ（５ｘ７）を作成する

In [6]:
import torch
a = torch.empty(5, 7, dtype= torch.float)

Mean = 0 と　VAR = 1の正規分布でランダム化されたdoubleテンソルを初期化する。

In [7]:
a = torch.randn(5, 7, dtype=torch.double)
print(a)
print(a.size())

tensor([[ 0.0228,  1.1144,  0.0281, -0.1241,  0.3339,  1.0471,  0.3430],
        [ 1.7164,  0.2653, -0.7943, -0.2315,  2.3551,  0.9732,  0.4003],
        [-0.4705, -0.3748,  0.6822, -0.8748,  0.8749,  1.2042, -0.1023],
        [-0.0992,  0.1603, -0.0323, -0.5624,  0.5819,  1.3144, -0.9819],
        [-0.0891,  0.3610,  0.6540,  0.0280,  0.4342, -0.5718, -0.7619]], dtype=torch.float64)
torch.Size([5, 7])


# Inplace / Out-of-place

add は out-of-place バージョン, and add_ は  in-place バージョンになる。

In [19]:
a.fill_(3.5)
# aは3.5の値で満たされました

b = a.add_(4.0)
# a + 4.0 and then  b = a
# aは3.5の値をまだ満たされました。
# 3.5 + 4.0 = 7.5の値として、新しいｂ変数が返却された。

print(a, b)

tensor([[ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000]], dtype=torch.float64) tensor([[ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000],
        [ 7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000,  7.5000]], dtype=torch.float64)


# Zero Indexing

In [27]:
b = a[0, 3] # select 1st row, 4th column from a
print(b)

tensor(7.5000, dtype=torch.float64)


In [28]:
b = a[:, 3:5]  # selects all rows, 4th column and  5th column from a
print(b)

tensor([[ 7.5000,  7.5000],
        [ 7.5000,  7.5000],
        [ 7.5000,  7.5000],
        [ 7.5000,  7.5000],
        [ 7.5000,  7.5000]], dtype=torch.float64)


# No camel casing

In [31]:
x = torch.ones(5, 5)
print(x)

tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])


In [33]:
z = torch.empty(5,7, dtype=torch.float)
z[:,0] = 10
z[:,1] = 100
print(z)

tensor([[  10.0000,  100.0000,    0.0000,    0.0000,    0.0000,    0.0000,
            0.0000],
        [  10.0000,  100.0000,    0.0000,    0.0000,    0.0000,    0.0000,
            0.0000],
        [  10.0000,  100.0000,    0.0000,    0.0000,    0.0000,    0.0000,
            0.0000],
        [  10.0000,  100.0000,    0.0000,    0.0000,    0.0000,    0.0000,
            0.0000],
        [  10.0000,  100.0000,    0.0000,    0.0000,    0.0000,    0.0000,
            0.0000]])


# Converting torch Tensor to numpy Array

In [34]:
a = torch.ones(5)
print(a)


tensor([ 1.,  1.,  1.,  1.,  1.])


In [35]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [36]:
a.add_(1)
print(a)
print(b)    # see how the numpy array changed in value

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


# Converting numpy Array to torch Tensor

In [37]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # see how changing the np array changed the torch Tensor automatically

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


# CUDA Tensors

In [ ]:
if torch.cuda.is_available():
    
    # creates a LongTensor and transfers it
    # to GPU as torch.cuda.LongTensor
    a = torch.full((10,), 3, device=torch.device("cuda"))
    print(type(a))
    b = a.to(torch.device("cpu"))